### ISSUE TITLE
Random crashes on creating new Instance of 'V8ScriptEngine' - Library Class Dll file, Again??!

### ISSUE THREAD

**Issue by GameHackerPM** [microsoft/ClearScript#294] opened 2021-10-04 18:08 UTC
Hi, I currently upgraded to version 7.1.6 and seems to have problem with random crashes again like in issue #268 It's kinda similar to that issue so far, but now it has more info from before so I think you might figure out faster.

![This is an image](https://i.ibb.co/Qkmhyzp/image-1.png)

Environment
- .NET Framework 4.6.2
- Windows 10 Pro

I rolled back to version 7.1.4 (Didn't test 7.1.5) as that seems to be working better without crashes like in 7.1.6!
Will report back if I found it got crashed too or any updates.

Thanks for your reading.

**Comment by ClearScriptLib** [comment] 2021-10-04 18:17
Hi @GameHackerPM,

This could be the same issue as #291. Would you be able to test [Version 7.1.7-preview](https://www.nuget.org/packages/Microsoft.ClearScript/7.1.7-preview)?

Thank you!

**Comment by GameHackerPM** [comment] 2021-10-04 20:17
Hi @ClearScriptLib,

Thanks for the fast reply.
I saw that issue before creating mine, but didn't know it could be the same issue so far. I'm currently testing the 7.1.7-preview to let you know how it goes in half an hour or something.

Thanks.

**Comment by GameHackerPM** [comment] 2021-10-04 20:41
After testing 20+ minutes, I can confirm that 7.1.7-preview fixed the issue. Before that it didn't even last for 10 minutes and crashes.

**Comment by ClearScriptLib** [comment] 2021-10-05 02:11
Thanks @GameHackerPM! Closing this issue as a duplicate of #291.

**Closed by ClearScriptLib** 2021-10-05 02:11 UTC
Labels: bug, duplicate
