### ISSUE TITLE
Add support for .NET Core

### ISSUE THREAD

**Issue by cilerler** [microsoft/ClearScript#9] opened 2017-08-10 15:13 UTC
When I try to add it from Nuget it says

```
Restoring packages for ...\ClassLibrary1.csproj...
Package ClearScript.V8 5.4.9 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package ClearScript.V8 5.4.9 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with .NETStandard,Version=v1.4.
Package restore failed. Rolling back package changes for 'ClassLibrary1'.
```

**Comment by ClearScriptLib** [comment] 2017-08-11 14:04
Unfortunately ClearScript depends on reflection and dynamic runtime APIs that are not covered by the current .NET Standard. Furthermore, it's V8 bridge is a mixed assembly and therefore requires .NET Framework.

**Comment by cilerler** [comment] 2017-08-11 14:12
Thank you, do you think it will be covered with .NET Standard 2?

**Comment by ClearScriptLib** [comment] 2017-08-11 14:36
Possibly. We'll keep this issue open and check again soon. Looks like .NET Standard 2.0 was finalized just yesterday!

**Comment by bangclash** [comment] 2017-10-04 20:42
Net Standard 2 support would be great.

**Comment by guillaumechervet** [comment] 2017-10-05 05:36
I am agree. Vert great :)

**Comment by wboevink** [comment] 2017-11-10 09:43
+1 .Net Core 2.0 support

**Comment by ipjohnson** [comment] 2017-11-22 16:44
@ClearScriptLib any news on supporting .netstandard 2.0?

**Comment by ClearScriptLib** [comment] 2017-11-24 19:54
Hi @ipjohnson,

We've analyzed the ClearScript assemblies, and it didn't look too bad. A couple dozen APIs, most of them related to COM interop, are not available on .NET Standard.

A bigger problem for ClearScript is its dependence on Windows. JScript and VBScript are Windows-specific, and ClearScriptV8 is mixed-mode (an assembly type that's only supported on Windows).

So even if it used 100% .NET Standard APIs, ClearScript would still be Windows-only. Unfortunately, at this point, the best bet for portability would be a fork based on Chakra Core.

Thanks!

**Comment by ipjohnson** [comment] 2017-11-24 20:04
@ClearScriptLib Thanks for the update.

**Comment by imsmart-tech** [comment] 2017-12-16 17:28
+1
That would be great, even if it's Windows-only. I develop on Windows so go for it. :-)

Do you have any timeline?

**Comment by Grauenwolf** [comment] 2018-01-07 18:52
Most of us could live without JScript and VBScript. What we're looking for is the ability to load modern JavaScript so we can do pre-rendering like they do in Node.

**Comment by ClearScriptLib** [comment] 2018-01-08 18:05
Thanks, @Grauenwolf. Just wondering, why are you looking for .NET Standard support? Do you wish to host your application in .NET Core or another runtime? Or are you interested in non-Windows platforms?

**Comment by cilerler** [comment] 2018-01-08 18:17
@ClearScriptLib it is crucial to move applications to **Docker** environment _(could be Linux, could be Windows, isn't that ERA we are in now)_ 😄  Please help us and implement a workaround. 🤗

**Comment by Grauenwolf** [comment] 2018-01-08 18:51
Mostly I am interested in ridding myself of dependences on Node.

Node is used a lot by UI devs for build steps and pre-rendering pages. ASP.NET Core could easily do the same thing if it could run the parsers written in JavaScript.

**Comment by Grauenwolf** [comment] 2018-01-08 18:54
Yes, running on non-Windows is a must. Nobody is going to consider replacing Node with ASP.NET if Linux support isn't an option.

**Comment by hiyelbaz** [comment] 2018-01-08 19:34
.Net Core on Linux +1

**Comment by guillaumechervet** [comment] 2018-01-09 06:29
V8 & .Net Core on Linux +1

**Comment by ClearScriptLib** [comment] 2018-01-09 16:20
Folks,

Thanks for clarifying your requirements.

Unfortunately ClearScript's V8 connector is implemented in C++/CLI and would have to be redeveloped from scratch to gain cross-platform capability.

Have you considered purely managed JavaScript solutions such as [Jint](https://github.com/sebastienros/jint)? There's also a portable solution based on V8 [here](https://github.com/rjamesnw/v8dotnet).

Cheers!

**Comment by ashutosh-kiddev** [comment] 2018-10-10 09:28
Hi, this is a great library and great work done by Clearscript team.We at Ubimax are trying to reuse some of our features from an existing windows application into a Unity/Hololens project. We used Clearscript for JS/C# bridging and it was great. But Clearscript seems not to be compatible with Unity. Is there any progress on making a .net standard/.net core supported version which is cross platform or if someone has tried making it usable with Unity/Hololens projects? Thanks in advance :)

**Comment by ClearScriptLib** [comment] 2018-10-10 15:50
Hi @ashutosh-kiddev,

Thanks for your kind words. Unfortunately redeveloping ClearScriptV8 for compatibility with the current .NET Core would be a large project.

Instead we're hoping that .NET Core will eventually gain the platform features that ClearScriptV8 requires. To that end we're observing CoreCLR issues [#18013](https://github.com/dotnet/coreclr/issues/18013) and [#659](https://github.com/dotnet/coreclr/issues/659).

Cheers!

**Comment by ashutosh-kiddev** [comment] 2018-10-11 07:28
@ClearScriptLib Thanks a lot for the quick response. We will keep looking for the progress and hope it will this gets done sooner than later. :)

**Comment by smokeelow** [comment] 2019-04-02 19:30
@ClearScriptLib  Looks like that a lot of progress has been made on these two  [#18013 ](https://github.com/dotnet/coreclr/issues/18013), [#659](https://github.com/dotnet/coreclr/issues/659)

Does it mean that we can expect ClearScriptV8 support for .Net Core in the near future?

**Comment by ClearScriptLib** [comment] 2019-04-02 20:33
@smokeelow Our interest in bringing ClearScript to .NET Core remains very high. If and when .NET Core officially gains support for mixed-mode assemblies, supporting it will become our top priority.

**Comment by cilerler** [comment] 2019-06-27 16:32
@ClearScriptLib https://github.com/dotnet/coreclr/issues/18013 has been closed :wink:

**Comment by WhitWaldo** [comment] 2019-07-06 00:50
> @ClearScriptLib [dotnet/coreclr#18013](https://github.com/dotnet/coreclr/issues/18013) has been closed 😉

It has, but with the caveat that only the .NET side is completed and that remaining work on the C++/CLI side is being internally tracked.

**Comment by cilerler** [comment] 2019-07-06 01:51
Any chance to make this happen in .NetCore3?

**Comment by daniel-schroeder-zeiss** [comment] 2019-07-22 11:33
I'd like to add that even a windows only .Net Standard or Core support would be appreciated. Microsoft is quite clearly communicating that this will be the future. So we would like to move our project to .Net Core even though it is windows only.

**Comment by LeaFrock** [comment] 2019-08-28 07:13
As i see above, many developers like me are very eager for your support on .Net Core. Maybe my expectation is a little bit higher. I hope ClearScript can be used on .Net Core and cross platforms(not windows-only). It should be totally available on .Net Core(/Standard).

> Unfortunately redeveloping ClearScriptV8 for compatibility with the current .NET Core would be a large project.
.Net itself has been redeveloped and keeps going on. ClearScript is also a official project which represents trust and advance in our minds. So if .NET Core 3.0 doesn't gain support for mixed-mode assemblies, redeveloping a project as 'ClearScript.Core', rather than waiting for something, should be more meaningful to us. The .Net Framework will be a history, and don't let it be a stumbling block——unless you would abandon this project in the future.

**Comment by cilerler** [comment] 2019-09-23 21:30
@ClearScriptLib FYI

> I want to share a quick update on this. The latest on the C++/CLI roadmap can be found on our C++ blog here: https://devblogs.microsoft.com/cppblog/the-future-of-cpp-cli-and-dotnet-core-3/
> 
> .NET Core support for C++/CLI is coming in .NET Core 3.1 which is shipping with Visual Studio 2019 16.4.

**Comment by cilerler** [comment] 2019-10-22 20:16
@ClearScriptLib any update on this? Would you please provide a status update.  Thanks in advance

**Comment by PlonkaAdam** [comment] 2019-10-23 15:46
as .NET Core vNext will be called .NET 5.0 and .NET Framework 4.8 is the last version which suggests an upgrade from .NET Framework 4.8 to .NET 5.0 will be the only and inevitable upgrade path for windows applications - are there real chances of support for .NET 5.0 (at least windows only)?

**Comment by cilerler** [comment] 2019-10-23 16:16
@PlonkaAdam No need to blur the water, read the entire issue, please. We have a great chance to receive .NET 3 upgrade, based on what @ClearScriptLib said above. There were two blocking issues, which both resolved as far as I know. However, the only downside will be running it on the Windows environment, but it will be still feasible to use .NET Core 3.

**Comment by ClearScriptLib** [comment] 2019-10-23 16:50
Hi @cilerler,

An update:
- The main ClearScript library is almost entirely compatible with .NET Core 3.0. We're ironing out a few remaining issues.
- We're awaiting the final release of .NET Core 3.1 to begin porting the V8 interface.
- The rest (test libraries, NuGet package, etc.) will follow the V8 work.

Assuming that .NET Core 3.1 fully supports mixed-mode assemblies, we should have a release targeting that platform at some point. Unfortunately, as ClearScript is a side project, we can't commit to any definite timelines.

Thanks!

**Comment by cilerler** [comment] 2019-10-23 16:53
That is fantastic news @ClearScriptLib. Thank you very much!

**Comment by LeaFrock** [comment] 2019-10-27 14:05
@ClearScriptLib Waiting for good news! Thanks!

**Comment by tombatron** [comment] 2019-12-03 21:33
# WOO HOO!

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/

**Comment by colonelchlorine** [comment] 2019-12-05 02:58
When the post says "C++/CLI is only enabled on Windows", what does that mean in terms of the V8 interface port & ClearScript working on other platforms (e.g Linux)?

**Comment by ClearScriptLib** [comment] 2019-12-05 14:49
Hi @colonelchlorine,

.NET Core 3.1 supports mixed assemblies, but only on Windows. ClearScript won't be portable to other operating systems until that changes.

Cheers!

**Comment by ClearScriptLib** [comment] 2019-12-18 16:44
[ClearScript 6.0](https://github.com/microsoft/ClearScript/releases/tag/6.0.0) added support for .NET Core 3.1.

**Comment by cilerler** [comment] 2019-12-18 17:19
![bitmoji](https://render.bitstrips.com/v2/cpanel/ed5c9c0f-c444-4b15-b96b-a66885184e6a-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)

**Comment by crowder** [comment] 2019-12-18 19:32
What remains to be done to enable this support for Linux?

**Comment by tombatron** [comment] 2019-12-18 20:26
They would have to rewrite the library to not by a C++/CLI library.

**Comment by ClearScriptLib** [comment] 2019-12-19 14:40
@crowder @tombatron Strictly speaking, the issue is not with C++/CLI but the fact that ClearScriptV8 is a _mixed assembly_ - one that packs managed and native code into a single file. Such assemblies are supported only on Windows, and our understanding is that Linux support would require kernel and toolchain modifications.

Anyway, because ClearScript now supports .NET Core, we're closing this issue. Please feel free to open new ones to report any problems you encounter with ClearScript on any supported platform.

**Closed by ClearScriptLib** 2019-12-19 14:40 UTC
Labels: enhancement, fixed
