### ISSUE TITLE
IIS V8 Win32Exception Error 

### ISSUE THREAD

**Issue by joelpontes** [microsoft/ClearScript#160] opened 2020-01-28 10:00 UTC
I'm trying to publish my ASP.Net Core 3.1 app width ClearScript 6.0 on IIS , Windows but i have this 
Error:

 System.ComponentModel.Win32Exception (126): 
The specified module could not be found
at Microsoft.ClearScript.Util.IJW.IJWHostLibrary.Load()     
at Microsoft.ClearScript.V8.V8Proxy.LoadAssemblyWithIJWHostLibrary()     
at Microsoft.ClearScript.V8.V8Proxy.GetAssembly()     
at Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type)     
at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)     
at Microsoft.ClearScript.V8.V8IsolateProxy.Create(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)     
at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)     
at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags)     
at Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints)     
at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)     
at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort)     
at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8ScriptEngineFlags flags, Int32 debugPort)    
 at Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8ScriptEngineFlags flags)     

IIS is using "AspNetCoreModuleV2" ,i copy all files to publish folder:
ClearScriptV8-32.dll
ClearScriptV8-64.dll
v8-ia32.dll
v8-x64.dll
v8-base-ia32.dll
v8-base-x64.dll
v8-libcpp-ia32.dll
v8-libcpp-x64.dll

When debug in visual studio i have no problem.
Any help or suggestions ?
Thanks

**Comment by ClearScriptLib** [comment] 2020-01-28 12:04
Hi @joelpontes,

Make sure you have the Visual Studio Redistributable libraries installed on your deployment machine. Download and install both the 32-bit and 64-bit versions: [[x86]](https://aka.ms/vs/16/release/vc_redist.x86.exe) [[x64]](https://aka.ms/vs/16/release/vc_redist.x64.exe).

Good luck!

**Comment by joelpontes** [comment] 2020-01-28 12:54
Yes i have instaled both on deployment machine but same problem.

Notice that on production they create a new folder ".\Microsoft\ClearScript\6.0.0\x64\IJW\ijwhost.dll" is this normal ?

**Comment by ClearScriptLib** [comment] 2020-01-28 13:55
>Notice that on production they create a new folder ".\Microsoft\ClearScript\6.0.0\x64\IJW\ijwhost.dll" is this normal?

That file - ijwhost.dll - is part of the .NET Core version of ClearScript. It's embedded in the main ClearScript assembly and unpacked into the file system on first run. It's supposed to be placed under the [LocalApplicationData](https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder) folder; is that not where it's going on your deployment machine?

In any case, we'd like to investigate this issue. Can you provide any details about your IIS deployment and your method of publishing your application?

**Comment by joelpontes** [comment] 2020-01-28 15:23
I create a dummy example to replicate the problem : https://github.com/joelpontes/ClearScriptTest 
I Deploy  app to a local folder using Visual Studio , then stop IIS and copy the Files to web site IIS folder and start IIS.
Application Pool of web site is  .NET CLR version : No Managed Code.

**Comment by ClearScriptLib** [comment] 2020-01-28 21:53
Hi @joelpontes,

Thanks for posting the sample project! We were able to reproduce your issue.

The problem, at least in our case, appears to have been related to application pool identities and permissions. Of the built-in accounts, only LocalSystem worked for us. We also tested with local and domain user accounts; they also worked.

Unfortunately we don't have a full explanation, so we'll keep this issue open and investigate. In the meantime we recommend that you try configuring your application pool to use an authenticated user identity.

Thanks!

**Comment by joelpontes** [comment] 2020-01-29 11:23
Yes change application pool identities and permissions to LocalSystem worked for me.
Thank you very much.

**Comment by ClearScriptLib** [comment] 2020-01-31 21:40
Hi @joelpontes,

We've identified the cause of the issue and will have a fix in the next ClearScript release.

Running your service as LocalSystem may not be wise from a security perspective. With our upcoming fix you'll be able to use least-privileged accounts, such as the application pool identity, for better safety.

Thanks!

**Comment by upsilondynamics** [comment] 2020-04-01 15:09
I am having a similar problem but only in Azure on only one of my Web projects, but not the other, no clue what the issue is:

      4/1/2020 2:45:30 PM	Method GenerateFlow: System.ComponentModel.Win32Exception (126): The specified module could not be found.

         at Microsoft.ClearScript.Util.IJW.IJWHostLibrary.Load()

         at Microsoft.ClearScript.V8.V8Proxy.LoadAssemblyWithIJWHostLibrary()

         at Microsoft.ClearScript.V8.V8Proxy.GetAssembly()

         at Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type)

         at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)

**Comment by upsilondynamics** [comment] 2020-04-01 15:20
@ClearScriptLib 

Segment of code failing:

`            //Instantiate the V8 Scripting Engine
            _engine = new V8ScriptEngine("JFlowScriptEngine")
            {
                AllowReflection = false,
                MaxRuntimeHeapSize = (UIntPtr) MaxRuntimeHeapSize,
                MaxRuntimeStackUsage = (UIntPtr) MaxRuntimeStackUsage
            };`

**Comment by ClearScriptLib** [comment] 2020-04-13 16:01
Fixed in [Version 6.0.1](https://github.com/microsoft/ClearScript/releases/tag/6.0.1).

**Closed by ClearScriptLib** 2020-04-13 16:01 UTC
Labels: bug, fixed
