### ISSUE TITLE
Add support for Xamarin.Android

### ISSUE THREAD

**Issue by ackava** [Microsoft/ClearScript#57] opened 2018-06-04 15:41 UTC

**Comment by ClearScriptLib** [comment] 2018-06-05 14:40
Closing as duplicate of Issue #9.

**Closed by ClearScriptLib** 2018-06-05 14:40 UTC
Labels: duplicate, enhancement

**Comment by ackava** [comment] 2018-06-07 15:21
@ClearScriptLib Will .NetStandard work on Xamarin.Android? or will it only be specific to windows?

**Comment by ClearScriptLib** [comment] 2018-06-07 15:46
@ackava .NET Standard is an API specification that Mono should support eventually if it doesn't already. However, ClearScript is unlikely to work on platforms other than Windows due to its reliance on [mixed assemblies](https://msdn.microsoft.com/en-us/library/x0w2664k.aspx).
