### ISSUE TITLE
V8 debugging breakpoints in VSCode

### ISSUE THREAD

**Issue by boukestam** [Microsoft/ClearScript#59] opened 2018-07-05 12:54 UTC
I'm trying to debug my javascript code with the VSCode debugger.
I have constructed my engine with the following code:
```c#
_engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging, 9222);
```
And added the following to my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to ClearScript V8 on port 9222",
            "type": "node",
            "request": "attach",
            "protocol": "inspector",
            "address": "localhost",
	    "port": 9222
        }
    ]
}
```
After starting my C# application and starting the debugger in vscode I try to set some breakpoints in javascript. But the breakpoints are not being verified (not turning red). If I then trigger the debugger with the following line:
```javascript
debugger;
```
VSCode breaks on that line as expected. From that moment on I can successfully place and trigger breakpoints in VSCode, they are also being verified (turning red). But at any point before triggering that first debugger statement, no breakpoints are being verified.

**Comment by ClearScriptLib** [comment] 2018-07-05 13:21
Hi @boukestam,

Without the `debugger` statement, what is your application doing when you attach the debugger? Is it already running the script in which you're trying to set a breakpoint?

Thanks!

**Comment by ClearScriptLib** [comment] 2018-07-05 14:10
Hmm, what is your ClearScript version? Did you build it yourself? Any modifications relative to the official source?

**Comment by boukestam** [comment] 2018-07-05 14:28
I'm using version 5.5.2 from nuget. Without any modifications.
I've noticed that when the debugger statement triggers it opens a new tab of the same source file with the annotation "read-only core module".
![image](https://user-images.githubusercontent.com/8492132/42329167-5baf01f0-8070-11e8-9afa-66e8210d1205.png)
I'm not sure why this happens, because the path passed to the V8ScriptEngine.Compile function is the same as my local file.

**Comment by ClearScriptLib** [comment] 2018-07-05 15:59
ClearScript currently strips paths out of `documentName` arguments (see Issue #46), so setting breakpoints in a script opened from the file system may not work.

You should be able to set breakpoints in any script opened from the "Loaded Scripts" section of VSC's "Debug" panel. Can you confirm that?

**Comment by boukestam** [comment] 2018-07-09 08:33
Hi, sorry for my late reply. Yes it works when I open the script from the loaded scripts section in vscode. However, this is not the expected behavior and will be difficult to explain to my developers. Is there any fix or workaround to get this to work? Being able to keep the path would be handy anyway since it would then show the path in the stacktrace.

**Comment by ClearScriptLib** [comment] 2018-07-11 05:55
No guarantees, but hopefully, yes. The next source release should be out in a few weeks, and we’ll try to include a back-compatible fix for this.

**Comment by ClearScriptLib** [comment] 2018-07-11 05:57
Closing as duplicate of #46.

**Closed by ClearScriptLib** 2018-07-11 05:58 UTC
Labels: duplicate, enhancement
